#nullable enable

using System;
using System.Linq;
using System.Text;
using System.Text.Json;
using System.Threading;
using System.Threading.Tasks;
using AiNetLinter.FastTests.Fixtures;
using AiNetLinter.Mcp;
using AiNetLinter.Mcp.Scope;
using AiNetLinter.Mcp.Tools.SymbolGraph;
using AiNetLinter.TestKit;
using ModelContextProtocol.Protocol;
using Xunit;

namespace AiNetLinter.FastTests.Mcp.Tools.SymbolGraph;

[Trait("Category", "Component")]
public sealed class FindSymbolScopeRankingTests
{
    [Fact]
    public void ValidateScopeType_UnknownValuePointsToScopeField()
    {
        var result = FindSymbolTool.ValidateScopeType("mixed").Error;

        Assert.NotNull(result);
        Assert.Contains("fieldPath: $.scopeType", TextOf(result!), StringComparison.Ordinal);
    }

    [Fact]
    public async Task ApplyFinalResponseBudget_SourceFindSymbolKeepsVisibleTextWithinBudget()
    {
        var documents = Enumerable.Range(1, 30)
            .Select(index => ($"Budget{index}.cs", $"namespace App; public class BudgetTarget{index} {{ }}"))
            .ToArray();
        using var fixture = CreateFixture(("App", documents, null));

        var original = await ExecuteAsync(fixture, "BudgetTarget", maxResults: 50);
        var projected = FindSymbolTool.ApplyFinalResponseBudget(original, 2_048);

        Assert.True(projected.IsError);
        var text = Assert.IsType<TextContentBlock>(Assert.Single(projected.Content)).Text;
        Assert.Contains("RESPONSE_BUDGET_TOO_SMALL", text, StringComparison.Ordinal);
        Assert.Contains("maxResponseBytes", text, StringComparison.Ordinal);
    }

    [Fact]
    public async Task ExecuteAsync_AllRanksExactProductionBeforeTestSubstring()
    {
        using var fixture = CreateFixture(
            ("App", [("Production.cs", "namespace App; public class Target {} public class TargetService {}")], null),
            ("App.Tests", [("TargetTests.cs", "namespace App.Tests; public class TargetTests {} public class TargetServiceTests {}")], ["App"]));

        var result = await ExecuteAsync(fixture, "Target", maxResults: 1);
        var text = TextOf(result);
        Assert.Contains("Production.cs", text, StringComparison.Ordinal);
        Assert.DoesNotContain("TargetTests.cs", text, StringComparison.Ordinal);
    }

    [Fact]
    public async Task ExecuteAsync_ProductionAndTestsAreDisjoint()
    {
        using var fixture = CreateFixture(
            ("App", [("Shared.cs", "namespace App; public class Shared {}")], null),
            ("App.Tests", [("SharedTests.cs", "namespace App.Tests; public class Shared {}")], ["App"]));

        var production = TextOf(await ExecuteAsync(fixture, "Shared", McpScopeType.Production));
        var tests = TextOf(await ExecuteAsync(fixture, "Shared", McpScopeType.Tests));

        Assert.Contains("Shared.cs", production, StringComparison.Ordinal);
        Assert.DoesNotContain("SharedTests.cs", production, StringComparison.Ordinal);
        Assert.Contains("SharedTests.cs", tests, StringComparison.Ordinal);
        Assert.DoesNotContain("Shared.cs", tests.Replace("SharedTests.cs", string.Empty, StringComparison.Ordinal), StringComparison.Ordinal);
    }

    [Fact]
    public async Task ExecuteAsync_GeneratedIsExcludedByDefaultAndMarkedWhenOptedIn()
    {
        using var fixture = CreateFixture(
            ("App", [
                ("Editable.cs", "namespace App; public class GeneratedTarget {}"),
                ("Generated.g.cs", "// <auto-generated />\nnamespace App; public class GeneratedTargetTwo {}") ], null));

        var defaultResult = TextOf(await ExecuteAsync(fixture, "GeneratedTarget"));
        var generatedResult = TextOf(await ExecuteAsync(fixture, "GeneratedTarget", includeGenerated: true));

        Assert.DoesNotContain("Generated.g.cs", defaultResult, StringComparison.Ordinal);
        Assert.Contains("Generated.g.cs", generatedResult, StringComparison.Ordinal);
    }

    [Fact]
    public async Task ExecuteAsync_PartialSymbolIsOneEntryWithAllLocations()
    {
        using var fixture = CreateFixture(
            ("App", [
                ("Partial.One.cs", "namespace App; public partial class PartialTarget { public void One() {} }"),
                ("Partial.Two.cs", "namespace App; public partial class PartialTarget { public void Two() {} }") ], null));

        var text = TextOf(await ExecuteAsync(fixture, "PartialTarget"));
        Assert.Contains("Partial.One.cs", text, StringComparison.Ordinal);
        Assert.Contains("Partial.Two.cs", text, StringComparison.Ordinal);
    }

    [Fact]
    public async Task ExecuteAsync_KindMismatchExposesAlternativesSeparately()
    {
        using var fixture = CreateFixture(
            ("App", [("Contract.cs", "namespace App; public interface KindAlternative {}") ], null));

        var text = TextOf(await ExecuteAsync(fixture, "KindAlternative", kind: "class"));
        Assert.Contains("Keine Treffer", text, StringComparison.Ordinal);
        Assert.Contains("interface", text, StringComparison.Ordinal);
    }

    [Fact]
    public async Task ExecuteAsync_CompletenessCountsOnlyFilteredPopulation()
    {
        using var fixture = CreateFixture(
            ("App", [("OnlyProduction.cs", "namespace App; public class FilteredTarget {}")], null),
            ("App.Tests", [("TestOne.cs", "namespace App.Tests; public class FilteredTarget {}"), ("TestTwo.cs", "namespace App.Tests; public class FilteredTargetTwo {}")], ["App"]));

        var text = TextOf(await ExecuteAsync(fixture, "FilteredTarget", McpScopeType.Production, maxResults: 1));
        Assert.Contains("OnlyProduction.cs", text, StringComparison.Ordinal);
        Assert.DoesNotContain("TestOne.cs", text, StringComparison.Ordinal);
    }

    private static async Task<CallToolResult> ExecuteAsync(
        McpInMemoryTestContext fixture,
        string pattern,
        McpScopeType scopeType = McpScopeType.All,
        bool includeGenerated = false,
        int maxResults = 50,
        string? kind = null) =>
        await FindSymbolTool.ExecuteAsync(new FindSymbolRequest(
            fixture.CreateServer(),
            NamePatterns: [pattern],
            Kind: kind,
            MaxResults: maxResults,
            CancellationToken.None,
            ScopeType: scopeType,
            IncludeGenerated: includeGenerated));

    private static string TextOf(CallToolResult result) =>
        Assert.IsType<TextContentBlock>(Assert.Single(result.Content)).Text;

    private static McpInMemoryTestContext CreateFixture(
        params (string Name, (string FileName, string Content)[] Documents, string[]? References)[] projects)
    {
        var specs = projects
            .Select(project => new ProjectSpec(project.Name, project.Documents, project.References))
            .ToArray();
        return new McpInMemoryTestContext(McpInMemoryTestContext.CreateScenario(specs));
    }
}
