#nullable enable

using System;
using System.Linq;
using System.Text;
using System.Text.Json;
using System.Threading;
using System.Threading.Tasks;
using AiNetLinter.FastTests.Fixtures;
using AiNetLinter.Mcp;
using AiNetLinter.Mcp.Scope;
using AiNetLinter.Mcp.Tools.SymbolGraph;
using AiNetLinter.TestKit;
using ModelContextProtocol.Protocol;
using Xunit;

namespace AiNetLinter.FastTests.Mcp.Tools.SymbolGraph;

[Trait("Category", "Component")]
public sealed class FindSymbolScopeRankingTests
{
    [Fact]
    public void ValidateScopeType_UnknownValuePointsToScopeField()
    {
        var result = FindSymbolTool.ValidateScopeType("mixed").Error;

        Assert.NotNull(result);
        Assert.Equal("$.scopeType", result!.StructuredContent!.Value.GetProperty("fieldPath").GetString());
    }

    [Fact]
    public async Task ApplyFinalResponseBudget_SourceFindSymbolKeepsCombinedWirePayloadWithinBudget()
    {
        var documents = Enumerable.Range(1, 30)
            .Select(index => ($"Budget{index}.cs", $"namespace App; public class BudgetTarget{index} {{ }}"))
            .ToArray();
        using var fixture = CreateFixture(("App", documents, null));

        var original = await ExecuteAsync(fixture, "BudgetTarget", maxResults: 50);
        var projected = FindSymbolTool.ApplyFinalResponseBudget(original, 2_048);

        Assert.NotEqual(true, projected.IsError);
        var text = Assert.IsType<TextContentBlock>(Assert.Single(projected.Content)).Text;
        var structured = projected.StructuredContent!.Value.GetRawText();
        Assert.True(
            Encoding.UTF8.GetByteCount(text) + Encoding.UTF8.GetByteCount(structured) <= 2_048);
        Assert.Contains(
            "maxResponseBytes",
            projected.StructuredContent.Value.GetProperty("truncatedBy").ToString(),
            StringComparison.Ordinal);
    }

    [Fact]
    public async Task ExecuteAsync_AllRanksExactProductionBeforeTestSubstring()
    {
        using var fixture = CreateFixture(
            ("App", [("Production.cs", "namespace App; public class Target {} public class TargetService {}")], null),
            ("App.Tests", [("TargetTests.cs", "namespace App.Tests; public class TargetTests {} public class TargetServiceTests {}")], ["App"]));

        var result = await ExecuteAsync(fixture, "Target", maxResults: 1);
        var batch = Deserialize(result);

        var match = Assert.Single(Assert.Single(batch.Results).Matches);
        Assert.EndsWith("App/Production.cs", match.Locations![0].FilePath, StringComparison.Ordinal);
        Assert.Equal("production", match.Locations[0].ScopeType);
    }

    [Fact]
    public async Task ExecuteAsync_ProductionAndTestsAreDisjoint()
    {
        using var fixture = CreateFixture(
            ("App", [("Shared.cs", "namespace App; public class Shared {}")], null),
            ("App.Tests", [("SharedTests.cs", "namespace App.Tests; public class Shared {}")], ["App"]));

        var production = Deserialize(await ExecuteAsync(fixture, "Shared", McpScopeType.Production));
        var tests = Deserialize(await ExecuteAsync(fixture, "Shared", McpScopeType.Tests));

        Assert.All(Assert.Single(production.Results).Matches, entry =>
            Assert.All(entry.Locations!, location => Assert.Equal("production", location.ScopeType)));
        Assert.All(Assert.Single(tests.Results).Matches, entry =>
            Assert.All(entry.Locations!, location => Assert.Equal("tests", location.ScopeType)));
    }

    [Fact]
    public async Task ExecuteAsync_GeneratedIsExcludedByDefaultAndMarkedWhenOptedIn()
    {
        using var fixture = CreateFixture(
            ("App", [
                ("Editable.cs", "namespace App; public class GeneratedTarget {}"),
                ("Generated.g.cs", "// <auto-generated />\nnamespace App; public class GeneratedTargetTwo {}") ], null));

        var defaultResult = Deserialize(await ExecuteAsync(fixture, "GeneratedTarget"));
        var generatedResult = Deserialize(await ExecuteAsync(fixture, "GeneratedTarget", includeGenerated: true));

        Assert.DoesNotContain(Assert.Single(defaultResult.Results).Matches, entry =>
            entry.Locations!.Any(location => location.SourceKind == "generated"));
        Assert.Contains(Assert.Single(generatedResult.Results).Matches, entry =>
            entry.Locations!.Any(location => location.SourceKind == "generated"));
    }

    [Fact]
    public async Task ExecuteAsync_PartialSymbolIsOneEntryWithAllLocations()
    {
        using var fixture = CreateFixture(
            ("App", [
                ("Partial.One.cs", "namespace App; public partial class PartialTarget { public void One() {} }"),
                ("Partial.Two.cs", "namespace App; public partial class PartialTarget { public void Two() {} }") ], null));

        var batch = Deserialize(await ExecuteAsync(fixture, "PartialTarget"));
        var match = Assert.Single(Assert.Single(batch.Results).Matches);

        Assert.Equal(2, match.Locations!.Count);
        Assert.Contains(match.Locations, location => location.FilePath.Contains("Partial.One.cs", StringComparison.Ordinal));
        Assert.Contains(match.Locations, location => location.FilePath.Contains("Partial.Two.cs", StringComparison.Ordinal));
    }

    [Fact]
    public async Task ExecuteAsync_KindMismatchExposesAlternativesSeparately()
    {
        using var fixture = CreateFixture(
            ("App", [("Contract.cs", "namespace App; public interface KindAlternative {}") ], null));

        var batch = Deserialize(await ExecuteAsync(fixture, "KindAlternative", kind: "class"));
        var pattern = Assert.Single(batch.Results);

        Assert.Empty(pattern.Matches);
        Assert.Contains("interface", pattern.KindAlternatives!);
        Assert.Equal(0, pattern.TotalCount);
    }

    [Fact]
    public async Task ExecuteAsync_CompletenessCountsOnlyFilteredPopulation()
    {
        using var fixture = CreateFixture(
            ("App", [("OnlyProduction.cs", "namespace App; public class FilteredTarget {}")], null),
            ("App.Tests", [("TestOne.cs", "namespace App.Tests; public class FilteredTarget {}"), ("TestTwo.cs", "namespace App.Tests; public class FilteredTargetTwo {}")], ["App"]));

        var batch = Deserialize(await ExecuteAsync(fixture, "FilteredTarget", McpScopeType.Production, maxResults: 1));
        var pattern = Assert.Single(batch.Results);

        Assert.Equal(1, pattern.TotalCount);
        Assert.Equal(1, pattern.ReturnedCount);
        Assert.False(pattern.IsTruncated);
        Assert.Equal("production", batch.Scope!.RequestedType);
        Assert.False(batch.Scope.IncludeGenerated);
    }

    private static async Task<CallToolResult> ExecuteAsync(
        McpInMemoryTestContext fixture,
        string pattern,
        McpScopeType scopeType = McpScopeType.All,
        bool includeGenerated = false,
        int maxResults = 50,
        string? kind = null) =>
        await FindSymbolTool.ExecuteAsync(new FindSymbolRequest(
            fixture.CreateServer(),
            NamePatterns: [pattern],
            Kind: kind,
            MaxResults: maxResults,
            CancellationToken.None,
            ScopeType: scopeType,
            IncludeGenerated: includeGenerated));

    private static FindSymbolBatchDto Deserialize(CallToolResult result) =>
        JsonSerializer.Deserialize<FindSymbolBatchDto>(
            result.StructuredContent!.Value.GetRawText(),
            McpJsonOptions.Default)!;

    private static McpInMemoryTestContext CreateFixture(
        params (string Name, (string FileName, string Content)[] Documents, string[]? References)[] projects)
    {
        var specs = projects
            .Select(project => new ProjectSpec(project.Name, project.Documents, project.References))
            .ToArray();
        return new McpInMemoryTestContext(McpInMemoryTestContext.CreateScenario(specs));
    }
}
