#nullable enable

using System;
using System.Linq;
using System.Threading;
using System.Threading.Tasks;
using AiNetLinter.Mcp.Scope;
using AiNetLinter.TestKit;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;
using Xunit;

namespace AiNetLinter.FastTests.Mcp.Scope;

[Trait("Category", "Unit")]
public sealed class McpScopeClassifierTests
{
    [Fact]
    public async Task ClassifyAsync_DelegatesProjectAndFileClassificationToTestDetector()
    {
        using var fixture = RoslynTestSolutionFactory.CreateSolution(
            @"C:\virtual\scope.slnx",
            new ProjectSpec("App", [("Service.cs", "namespace App; public class Service {}")]),
            new ProjectSpec(
                "App.Tests",
                [("ServiceTests.cs", "namespace App.Tests; public class ServiceTests {}")],
                ProjectReferences: ["App"]));

        var classifier = new McpScopeClassifier();
        var production = fixture.Solution.Projects.Single(p => p.Name == "App").Documents.Single();
        var test = fixture.Solution.Projects.Single(p => p.Name == "App.Tests").Documents.Single();

        Assert.Equal(McpProjectKind.Production, (await classifier.ClassifyAsync(production)).ProjectKind);
        Assert.Equal(McpProjectKind.Tests, (await classifier.ClassifyAsync(test)).ProjectKind);
        Assert.True(classifier.MatchesScope(await classifier.ClassifyAsync(production), McpScopeType.All));
        Assert.False(classifier.MatchesScope(await classifier.ClassifyAsync(production), McpScopeType.Tests));
        Assert.True(classifier.MatchesScope(await classifier.ClassifyAsync(test), McpScopeType.Tests));
        Assert.False(classifier.MatchesScope(await classifier.ClassifyAsync(test), McpScopeType.Production));
    }

    [Fact]
    public async Task ClassifyAsync_AllKeepsUnknownVisible()
    {
        var projectId = ProjectId.CreateNewId("decompiled-assembly");
        using var workspace = new AdhocWorkspace();
        var solution = workspace.AddSolution(SolutionInfo.Create(
            SolutionId.CreateNewId(), VersionStamp.Create(), filePath: @"C:\virtual\unknown.slnx"));
        solution = solution.AddProject(ProjectInfo.Create(
            projectId,
            VersionStamp.Create(),
            "decompiled-assembly",
            "decompiled-assembly",
            LanguageNames.CSharp));
        var documentId = DocumentId.CreateNewId(projectId);
        solution = solution.AddDocument(
            documentId,
            "Decompiled.cs",
            "public class Decompiled {}",
            filePath: @"C:\virtual\unknown\Decompiled.cs");

        var scope = await new McpScopeClassifier().ClassifyAsync(solution.GetDocument(documentId)!, CancellationToken.None);

        Assert.Equal(McpProjectKind.Unknown, scope.ProjectKind);
        Assert.True(new McpScopeClassifier().MatchesScope(scope, McpScopeType.All));
        Assert.False(new McpScopeClassifier().MatchesScope(scope, McpScopeType.Production));
        Assert.False(new McpScopeClassifier().MatchesScope(scope, McpScopeType.Tests));
    }

    [Theory]
    [InlineData("obj/Generated.cs")]
    [InlineData("src/Feature.g.cs")]
    [InlineData("src/Feature.g.i.cs")]
    [InlineData("src/Feature.generated.cs")]
    [InlineData("src/Feature.designer.cs")]
    [InlineData("src/Feature.GENERATED.CS")]
    public async Task ClassifyAsync_GeneratedPathConventionsAreMarked(string path)
    {
        using var fixture = RoslynTestSolutionFactory.CreateSolution(
            @"C:\virtual\generated.slnx",
            new ProjectSpec("App", [(path, "public class Generated {}")], VirtualProjectDirectory: "src/App"));
        var document = fixture.Solution.Projects.Single().Documents.Single();

        var scope = await new McpScopeClassifier().ClassifyAsync(document);

        Assert.Equal(McpSourceKind.Generated, scope.SourceKind);
    }

    [Fact]
    public async Task ClassifyAsync_GeneratedHeaderAndAttributeAreMarked()
    {
        using var headerFixture = RoslynTestSolutionFactory.CreateSolution(
            @"C:\virtual\header.slnx",
            new ProjectSpec("App", [("Header.cs", "// <auto-generated />\npublic class Generated {}")]),
            new ProjectSpec("App2", [("Attribute.cs", "[System.CodeDom.Compiler.GeneratedCode(\"generator\", \"1\")] public class Generated {}") ]));
        var documents = headerFixture.Solution.Projects.SelectMany(p => p.Documents).ToArray();
        var classifier = new McpScopeClassifier();

        foreach (var document in documents)
        {
            Assert.Equal(McpSourceKind.Generated, (await classifier.ClassifyAsync(document)).SourceKind);
        }
    }

    [Fact]
    public async Task ClassifyAsync_CacheIsBoundToSnapshotAndDocumentId()
    {
        using var fixture = RoslynTestSolutionFactory.CreateSolution(
            @"C:\virtual\cache.slnx",
            new ProjectSpec("App", [("Shared.cs", "public class Shared {}")]),
            new ProjectSpec("App2", [("Shared.cs", "public class Shared {}") ]));
        var classifier = new McpScopeClassifier();
        var first = fixture.Solution.Projects.First().Documents.Single();
        var second = fixture.Solution.Projects.Last().Documents.Single();

        Assert.Equal(McpSourceKind.Editable, (await classifier.ClassifyAsync(first)).SourceKind);
        Assert.Equal(McpSourceKind.Editable, (await classifier.ClassifyAsync(second)).SourceKind);

        var changedSolution = fixture.Solution.WithDocumentText(
            first.Id,
            SourceText.From("// <auto-generated />\npublic class Shared {}"));
        var changed = changedSolution.GetDocument(first.Id)!;

        Assert.Equal(McpSourceKind.Generated, (await classifier.ClassifyAsync(changed)).SourceKind);
        Assert.Equal(McpSourceKind.Editable, (await classifier.ClassifyAsync(second)).SourceKind);
        Assert.Equal(3, classifier.CachedEntryCount);
    }

    [Theory]
    [InlineData(null, 0)]
    [InlineData("", 0)]
    [InlineData("all", 0)]
    [InlineData("production", 1)]
    [InlineData("tests", 2)]
    [InlineData(" TESTS ", 2)]
    public void TryParseScopeType_AcceptsOnlyTheThreeScopeValues(string? value, int expected)
    {
        Assert.True(McpScopeTypeValidator.TryParse(value, out var actual, out var fieldPath));
        Assert.Equal((McpScopeType)expected, actual);
        Assert.Null(fieldPath);
    }

    [Theory]
    [InlineData("mixed")]
    [InlineData("unknown")]
    [InlineData("prod")]
    public void TryParseScopeType_RejectsUnknownValuesAtScopeTypeField(string value)
    {
        Assert.False(McpScopeTypeValidator.TryParse(value, out _, out var fieldPath));
        Assert.Equal("$.scopeType", fieldPath);
    }
}
