#nullable enable

using System;
using System.Linq;
using System.Threading;
using System.Threading.Tasks;
using AiNetLinter.Mcp;
using AiNetLinter.Mcp.Scope;
using AiNetLinter.Mcp.Tools.FeatureContext;
using AiNetLinter.TestKit;
using Xunit;

namespace AiNetLinter.FastTests.Mcp.Tools.FeatureContext;

[Trait("Category", "Component")]
public sealed class GetFeatureContextToolScopeTests
{
    [Fact]
    public async Task ExecuteAsync_ScopeFiltersCallersAndTestEvidenceButKeepsDeclarationAsSeed()
    {
        using var scenario = GetFeatureContextToolTests.CreateFullTestScenario();
        var state = new McpCodeGraphServer(McpCodeGraphServerOptions.From(
            new McpCodeGraphServerOptionsFromParameters(null, Config: TestHelper.CreateDefaultConfig(), ReadOnlySolutionSnapshot: scenario.Solution)));

        var production = await GetFeatureContextTool.ExecuteAsync(state,
            new FeatureContextOptions("Calculator.Add", IncludeMetrics: false, IncludeViolations: false,
                Scope: new McpScopeInput(McpScopeType.Production, false)), CancellationToken.None);
        var tests = await GetFeatureContextTool.ExecuteAsync(state,
            new FeatureContextOptions("Calculator.Add", IncludeMetrics: false, IncludeViolations: false,
                Scope: new McpScopeInput(McpScopeType.Tests, false)), CancellationToken.None);

        var productionText = Assert.IsType<ModelContextProtocol.Protocol.TextContentBlock>(Assert.Single(production.Content)).Text;
        var testsText = Assert.IsType<ModelContextProtocol.Protocol.TextContentBlock>(Assert.Single(tests.Content)).Text;
        Assert.Contains("Consumer.Run", productionText, StringComparison.Ordinal);
        Assert.DoesNotContain("CalculatorTests.cs", productionText, StringComparison.Ordinal);
        Assert.DoesNotContain("Consumer.Run", testsText, StringComparison.Ordinal);
        Assert.Contains("CalculatorTests.cs", testsText, StringComparison.Ordinal);
    }

    [Fact]
    public async Task ExecuteAsync_TypeSeedDoesNotProjectPartialMembersOutsideScope()
    {
        using var scenario = RoslynTestSolutionFactory.CreateSolution(
            @"C:\virtual\FeatureContextPartialScope.slnx",
            new ProjectSpec("App", [
                ("Shared.cs", "namespace App; public partial class Shared { public void Production() { } }"),
                ("SharedTests.cs", "namespace App; public partial class Shared { public void TestOnly() { } }")
            ], VirtualProjectDirectory: "src/App"));
        var state = new McpCodeGraphServer(McpCodeGraphServerOptions.From(
            new McpCodeGraphServerOptionsFromParameters(null, Config: TestHelper.CreateDefaultConfig(), ReadOnlySolutionSnapshot: scenario.Solution)));

        var result = await GetFeatureContextTool.ExecuteAsync(state,
            new FeatureContextOptions("Shared", IncludeCallers: false, IncludeTests: false, IncludeMetrics: false, IncludeViolations: false,
                Scope: new McpScopeInput(McpScopeType.Production, false)), CancellationToken.None);
        var text = Assert.IsType<ModelContextProtocol.Protocol.TextContentBlock>(Assert.Single(result.Content)).Text;
        Assert.Contains("Production", text, StringComparison.Ordinal);
        Assert.DoesNotContain("TestOnly", text, StringComparison.Ordinal);
    }

    [Fact]
    public async Task ExecuteAsync_GeneratedCallersAreExcludedOrExplicitlyMarked()
    {
        using var scenario = RoslynTestSolutionFactory.CreateSolution(
            @"C:\virtual\FeatureContextGeneratedCaller.slnx",
            new ProjectSpec("App", [
                ("Target.cs", "namespace App; public class Target { public void Run() { } }"),
                ("GeneratedCaller.cs", "// <auto-generated />\nnamespace App; public class GeneratedCaller { public void Call() { new Target().Run(); } }")
            ], VirtualProjectDirectory: "src/App"));
        var state = new McpCodeGraphServer(McpCodeGraphServerOptions.From(
            new McpCodeGraphServerOptionsFromParameters(null, Config: TestHelper.CreateDefaultConfig(), ReadOnlySolutionSnapshot: scenario.Solution)));
        var excluded = await GetFeatureContextTool.ExecuteAsync(state,
            new FeatureContextOptions("Target.Run", IncludeTests: false, IncludeMetrics: false, IncludeViolations: false,
                Scope: new McpScopeInput(McpScopeType.All, false)), CancellationToken.None);
        var included = await GetFeatureContextTool.ExecuteAsync(state,
            new FeatureContextOptions("Target.Run", IncludeTests: false, IncludeMetrics: false, IncludeViolations: false,
                Scope: new McpScopeInput(McpScopeType.All, true)), CancellationToken.None);
        var excludedText = Assert.IsType<ModelContextProtocol.Protocol.TextContentBlock>(Assert.Single(excluded.Content)).Text;
        var includedText = Assert.IsType<ModelContextProtocol.Protocol.TextContentBlock>(Assert.Single(included.Content)).Text;
        Assert.DoesNotContain("GeneratedCaller", excludedText, StringComparison.Ordinal);
        Assert.Contains("GeneratedCaller", includedText, StringComparison.Ordinal);
        Assert.Contains("generated", includedText, StringComparison.OrdinalIgnoreCase);
    }
}
