#nullable enable

using System;
using System.Text.Json;
using System.Linq;
using System.Threading;
using System.Threading.Tasks;
using AiNetLinter.Mcp;
using AiNetLinter.Mcp.Scope;
using AiNetLinter.Mcp.Tools.FeatureContext;
using AiNetLinter.TestKit;
using Xunit;

namespace AiNetLinter.FastTests.Mcp.Tools.FeatureContext;

[Trait("Category", "Component")]
public sealed class GetFeatureContextToolScopeTests
{
    [Fact]
    public async Task ExecuteAsync_ScopeFiltersCallersAndTestEvidenceButKeepsDeclarationAsSeed()
    {
        using var scenario = GetFeatureContextToolTests.CreateFullTestScenario();
        var state = new McpCodeGraphServer(McpCodeGraphServerOptions.From(
            new McpCodeGraphServerOptionsFromParameters(null, Config: TestHelper.CreateDefaultConfig(), ReadOnlySolutionSnapshot: scenario.Solution)));

        var production = await GetFeatureContextTool.ExecuteAsync(state,
            new FeatureContextOptions("Calculator.Add", IncludeMetrics: false, IncludeViolations: false,
                Scope: new McpScopeInput(McpScopeType.Production, false)), CancellationToken.None);
        var tests = await GetFeatureContextTool.ExecuteAsync(state,
            new FeatureContextOptions("Calculator.Add", IncludeMetrics: false, IncludeViolations: false,
                Scope: new McpScopeInput(McpScopeType.Tests, false)), CancellationToken.None);

        var productionPayload = production.StructuredContent!.Value.Deserialize<FeatureContextPayload>(McpJsonOptions.Default)!;
        var testsPayload = tests.StructuredContent!.Value.Deserialize<FeatureContextPayload>(McpJsonOptions.Default)!;
        Assert.Equal("production", productionPayload.Declaration.ScopeType);
        Assert.True(productionPayload.Declaration.IsSeed);
        Assert.Equal(2, productionPayload.Callers!.TotalCallers);
        Assert.All(productionPayload.Callers.CallSites, call => Assert.Equal("editable", call.SourceKind));
        Assert.Empty(productionPayload.Tests!.TestFiles);
        Assert.Equal(0, testsPayload.Callers!.TotalCallers);
        Assert.NotEmpty(testsPayload.Tests!.TestFiles);
        Assert.Equal("tests", testsPayload.Tests.Scope!.RequestedType);
    }

    [Fact]
    public async Task ExecuteAsync_TypeSeedDoesNotProjectPartialMembersOutsideScope()
    {
        using var scenario = RoslynTestSolutionFactory.CreateSolution(
            @"C:\virtual\FeatureContextPartialScope.slnx",
            new ProjectSpec("App", [
                ("Shared.cs", "namespace App; public partial class Shared { public void Production() { } }"),
                ("SharedTests.cs", "namespace App; public partial class Shared { public void TestOnly() { } }")
            ], VirtualProjectDirectory: "src/App"));
        var state = new McpCodeGraphServer(McpCodeGraphServerOptions.From(
            new McpCodeGraphServerOptionsFromParameters(null, Config: TestHelper.CreateDefaultConfig(), ReadOnlySolutionSnapshot: scenario.Solution)));

        var result = await GetFeatureContextTool.ExecuteAsync(state,
            new FeatureContextOptions("Shared", IncludeCallers: false, IncludeTests: false, IncludeMetrics: false, IncludeViolations: false,
                Scope: new McpScopeInput(McpScopeType.Production, false)), CancellationToken.None);
        var payload = result.StructuredContent!.Value.Deserialize<FeatureContextPayload>(McpJsonOptions.Default)!;
        Assert.Contains(payload.Declaration.Members!, member => member.Contains("Production", StringComparison.Ordinal));
        Assert.DoesNotContain(payload.Declaration.Members!, member => member.Contains("TestOnly", StringComparison.Ordinal));
    }

    [Fact]
    public async Task ExecuteAsync_GeneratedCallersAreExcludedOrExplicitlyMarked()
    {
        using var scenario = RoslynTestSolutionFactory.CreateSolution(
            @"C:\virtual\FeatureContextGeneratedCaller.slnx",
            new ProjectSpec("App", [
                ("Target.cs", "namespace App; public class Target { public void Run() { } }"),
                ("GeneratedCaller.cs", "// <auto-generated />\nnamespace App; public class GeneratedCaller { public void Call() { new Target().Run(); } }")
            ], VirtualProjectDirectory: "src/App"));
        var state = new McpCodeGraphServer(McpCodeGraphServerOptions.From(
            new McpCodeGraphServerOptionsFromParameters(null, Config: TestHelper.CreateDefaultConfig(), ReadOnlySolutionSnapshot: scenario.Solution)));
        var excluded = await GetFeatureContextTool.ExecuteAsync(state,
            new FeatureContextOptions("Target.Run", IncludeTests: false, IncludeMetrics: false, IncludeViolations: false,
                Scope: new McpScopeInput(McpScopeType.All, false)), CancellationToken.None);
        var included = await GetFeatureContextTool.ExecuteAsync(state,
            new FeatureContextOptions("Target.Run", IncludeTests: false, IncludeMetrics: false, IncludeViolations: false,
                Scope: new McpScopeInput(McpScopeType.All, true)), CancellationToken.None);
        var excludedPayload = excluded.StructuredContent!.Value.Deserialize<FeatureContextPayload>(McpJsonOptions.Default)!;
        var includedPayload = included.StructuredContent!.Value.Deserialize<FeatureContextPayload>(McpJsonOptions.Default)!;
        Assert.Empty(excludedPayload.Callers!.CallSites);
        Assert.Single(includedPayload.Callers!.CallSites);
        Assert.Equal("generated", includedPayload.Callers.CallSites[0].SourceKind);
    }
}
