<Project Sdk="Microsoft.NET.Sdk">

  <Import Project="../../tests/AiNetLinter.TestProject.props" />

  <PropertyGroup>
    <RunSettingsFilePath>$(MSBuildThisFileDirectory)../../.runsettings</RunSettingsFilePath>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="coverlet.collector">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="xunit.runner.visualstudio">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="xunit.v3.assert" />
    <PackageReference Include="xunit.v3.core" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="Xunit" />
    <Using Include="AiNetLinter.TestKit" />
    <Using Include="AiNetLinter.Mcp.Assemblies.Analysis" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\AiNetLinter\AiNetLinter.csproj" />
    <ProjectReference Include="..\AiNetLinter.TestKit\AiNetLinter.TestKit.csproj" />
  </ItemGroup>

</Project>
